-- OSNOVNE TABLICE
CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) UNIQUE NOT NULL,
  pass_hash VARCHAR(255) NOT NULL,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(60) NOT NULL,
  verified TINYINT(1) DEFAULT 0,
  verify_token VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS providers(
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  skills TEXT,
  location VARCHAR(255),
  bio TEXT,
  reviews_enabled TINYINT(1) DEFAULT 1,
  quiet_from VARCHAR(5) DEFAULT '18:00',
  quiet_to   VARCHAR(5) DEFAULT '07:00',
  lat DECIMAL(9,6) NULL,
  lng DECIMAL(9,6) NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_users_name  ON users (name);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_providers_latlng ON providers (lat, lng);
